### DISCUSSION TITLE
Unable to make crate examples

### DISCUSSION THREAD

**Discussion by zmitchell** [PyO3/pyo3#2055] [Questions] [answered]
I've made a library crate using `maturin` and I'd like to make some examples so that I can have a binary to profile with stuff like `flamegraph`. This is my project structure:
```
ham2spec/
    src/
        lib.rs
    examples/
        my_example.rs
    Cargo.toml
    pyproject.toml
```
This is (a simplified version of) what my example looks like:
```rust
use ham2spec::some_func;

fn main() {
    let foo = some_func();
}
```
I also have the example listed in my `Cargo.toml`:
```toml
[[example]]
name = "my_example"
path = "examples/my_example.rs"
```
I'm getting the error `unresolved import 'ham2spec'`. It's my understanding that directly adding crates via `extern crate` is not needed with recent versions of Rust. I added `extern crate ham2spec` anyway and I get the error `can't find crate for 'ham2spec'`.

So, what am I doing wrong?

**Comment by adamreichold** [comment, marked as answer]
Can you post the full example somewhere? Or at least the content of `Cargo.toml`?

**Reply by zmitchell** [reply]
Here's the example:
```rust
extern crate ham2spec;
use ham2spec::compute_stick_spectrum;
use numpy::ndarray::{Array1, Array2};

// These are known-good results we'll test against
const BRIXNER_HAM: [f32; 49] = [
    // 7x7 matrix unraveled
    1.242000000000000000e+04,
    -1.060000000000000000e+02,
    8.000000000000000000e+00,
    -5.000000000000000000e+00,
    6.000000000000000000e+00,
    -8.000000000000000000e+00,
    -4.000000000000000000e+00,
    -1.060000000000000000e+02,
    1.256000000000000000e+04,
    2.800000000000000000e+01,
    6.000000000000000000e+00,
    2.000000000000000000e+00,
    1.300000000000000000e+01,
    1.000000000000000000e+00,
    8.000000000000000000e+00,
    2.800000000000000000e+01,
    1.214000000000000000e+04,
    -6.200000000000000000e+01,
    -1.000000000000000000e+00,
    -9.000000000000000000e+00,
    1.700000000000000000e+01,
    -5.000000000000000000e+00,
    6.000000000000000000e+00,
    -6.200000000000000000e+01,
    1.231500000000000000e+04,
    -7.000000000000000000e+01,
    -1.900000000000000000e+01,
    -5.700000000000000000e+01,
    6.000000000000000000e+00,
    2.000000000000000000e+00,
    -1.000000000000000000e+00,
    -7.000000000000000000e+01,
    1.246000000000000000e+04,
    4.000000000000000000e+01,
    -2.000000000000000000e+00,
    -8.000000000000000000e+00,
    1.300000000000000000e+01,
    -9.000000000000000000e+00,
    -1.900000000000000000e+01,
    4.000000000000000000e+01,
    1.250000000000000000e+04,
    3.200000000000000000e+01,
    -4.000000000000000000e+00,
    1.000000000000000000e+00,
    1.700000000000000000e+01,
    -5.700000000000000000e+01,
    -2.000000000000000000e+00,
    3.200000000000000000e+01,
    1.240000000000000000e+04,
];
const BRIXNER_DIPOLE_MOMENTS: [f32; 21] = [
    // 7x3 matrix unraveled, one dipole moment per row
    -7.409999999999999920e-01,
    -5.605999999999999872e-01,
    -3.695999999999999841e-01,
    -8.570999999999999730e-01,
    5.038000000000000256e-01,
    -1.073000000000000065e-01,
    -1.970999999999999974e-01,
    9.574000000000000288e-01,
    -2.109999999999999931e-01,
    -7.992000000000000215e-01,
    -5.335999999999999632e-01,
    -2.766000000000000125e-01,
    -7.368999999999999995e-01,
    6.558000000000000496e-01,
    1.640999999999999959e-01,
    -1.350000000000000089e-01,
    -8.791999999999999815e-01,
    4.568999999999999728e-01,
    -4.950999999999999845e-01,
    -7.083000000000000407e-01,
    -5.030999999999999917e-01,
];
const BRIXNER_PIG_POS: [f32; 21] = [
    // 7x3 matrix unraveled, one position vector per row
    2.625349998474121094e+01,
    2.782999992370605469e+00,
    -1.110700035095214844e+01,
    1.554899978637695312e+01,
    -1.585500001907348633e+00,
    -1.687949943542480469e+01,
    3.403500080108642578e+00,
    -1.370650005340576172e+01,
    -1.425450038909912109e+01,
    6.876500129699707031e+00,
    -2.091850090026855469e+01,
    -6.376999855041503906e+00,
    1.937750053405761719e+01,
    -1.849099922180175781e+01,
    -1.491500020027160645e+00,
    2.174550056457519531e+01,
    -7.323999881744384766e+00,
    3.115000128746032715e-01,
    1.058049964904785156e+01,
    -8.205499649047851562e+00,
    -5.826499938964843750e+00,
];

macro_rules! brixner_ham {
    () => {
        Array2::from_shape_vec((7, 7), Vec::from(BRIXNER_HAM)).unwrap()
    };
}
macro_rules! brixner_dipole_moments {
    () => {
        Array2::from_shape_vec((7, 3), Vec::from(BRIXNER_DIPOLE_MOMENTS)).unwrap()
    };
}
macro_rules! brixner_pig_pos {
    () => {
        Array2::from_shape_vec((7, 3), Vec::from(BRIXNER_PIG_POS)).unwrap()
    };
}

fn main() {
    let ham = brixner_ham!();
    let mus = brixner_dipole_moments!();
    let pos = brixner_pig_pos!();
    let sticks = compute_stick_spectrum(ham.view(), mus.view(), pos.view());
}
```

`Cargo.toml`
```toml
[package]
name = "ham2spec"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ham2spec"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
numpy = "0.15.0"
lapack = "0.19.0"
lapack-src = { version = "0.8.0", features = ["accelerate"]}
ndarray = { version = "0.15.0", features = ["approx-0_5"] }
approx = "0.5.0"

[dev-dependencies]
criterion = "0.3"

[[example]]
name = "stick_spectrum"
path = "examples/stick_spectrum.rs"

[[bench]]
name = "stick_spectrum"
harness = false
```

**Reply by adamreichold** [reply]
I am not completely sure, but I think
```toml
crate-type = ["cdylib"]
```
is the culprit as it means only a shared library is built whereas the example needs a Rust library to link against, i.e.
```toml
crate-type = ["rlib", "cdylib"]
```

**Reply by zmitchell** [reply]
Ok so adding `"rlib"` allows the example to pick up my crate, but now I'm getting linker errors when I run `cargo run --example stick_spectrum`. If I remove the `"cdylib"` the linker errors go away and the example runs properly. So now my question is how do I use `rlib` when I want to run examples and `cdylib` when I'm building wheels?

**Reply by mejrs** [reply]
I think this is one of those things that's just not really supported in cargo examples. It's a nice feature but it doesn't feel very polished.

We benchmark some of our own examples when running pyo3's CI. Can you try what we do?

**Reply by zmitchell** [reply]
I really just needed a binary to run a profiler on, so switching `crate-type` when I need to do that works well enough at the moment. Thanks for your help!

**Reply by adamreichold** [reply]
IIRC, for this to work out, you need to make the `extension-module` feature optional, i.e. instead of
```toml
pyo3 = { version = "0.15.1", features = ["extension-module"] }
```
do
```toml
[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = "0.15.1"
```
and run your example with
```
> cargo run --no-default-features --example stick_spectrum
```
