### DISCUSSION TITLE
how to set custom path to libpython3.so?

### DISCUSSION THREAD

**Discussion by properchopsticks** [PyO3/pyo3#3053] [Questions] [answered]
hi,

i'm working at a project right now and i would like to embed the python interpreter within the rust main program but i would also like to have the python3.so embedded into the binary or at least have pyo3 use the so i provide, not the one installed on the os.

i tested this on windows and i noticed that the program maps the dll installed on the system into the address space of the program and calls apis from there but i would like to use my own version of the python3 library or even better have it completely embedded into the binary and have it mapped into memory at runtime and executed from there.

do you know how can someone embed the so into the binary? or at least make the binary only look for the so provided?

thanks

**Comment by adamreichold** [comment, marked as answer]
Did you have a look at the [PyOxidizer](https://github.com/indygreg/PyOxidizer) project? Maybe this fulfils your needs already?

**Reply by properchopsticks** [reply]
hey, thanks for the reply. i looked at pyoxidizer but it still wasn't quite what i was looking for. in the end i managed to statically link the python library by passing arguments to the linker in config.toml:
```toml
[build]
rustflags = [
    "-Ctarget-feature=+crt-static",
    "-Crelocation-model=static",
    "-L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu",
    "-L/usr/lib/x86_64-linux-gnu",
    "-lstatic=python3.10",
    "-lstatic=expat",
    "-lstatic=m",
    "-lstatic=z",
    "-lstatic=c",
    "-lstatic=util",
    "-lstatic=dl",
    "-lstatic=pthread"
    ]
```
oddly enough it doesn't work when trying to use the pyo3 module but in an empty project with no dependencies it works fine.
the problem then is that you have to implement your own python interpreter using the c apis.
