### DISCUSSION TITLE
How to not rebuild the crate everytime

### DISCUSSION THREAD

**Discussion by lmtr0** [PyO3/pyo3#3173] [Questions] [answered]
Hello there, good day!
I've noticed that every time I build my code, I've to rebuild the pyo3 crate. Is there anyway for me to only build it once?

**Comment by adamreichold** [comment]
I think this is a [known issue](https://github.com/PyO3/pyo3/issues/1708) with `rustup`?

**Reply by lmtr0** [reply]
Hmmm, I don't known

**Reply by lmtr0** [reply, marked as answer]
Using this config solves the problem:
```toml
# .cargo/config.toml
[env]
PYO3_PYTHON = "/usr/local/bin/python3"
```
