### DISCUSSION TITLE
Is it possible to make the python binding optional feature?

### DISCUSSION THREAD

**Discussion by NMZ0429** [PyO3/pyo3#3501] [Questions] [answered]
I am making a crate for both python and rust user. The structure of my crate is like below.

```shell
├── src
│   ├── lib.rs <- python binding
│   ├── core.rs <- pure rust functions
```

Currently, all rust functions are in `core.rs` and I wrapped them by another functions in `lib.rs` to use `#[pyfunction]` and `#[pymodule]` macros.

My question is that if it is possible to seperate the code for binding from `lib.rs` to another file and it only compiles only when user wants to use python binding. So ideally, it would be something like below.

```shell
├── src
│   ├── lib.rs
│   ├── python_binding.rs <- for python user
│   ├── core.rs <- pure rust functions
```

So if user compild it with a feature flag, `python_binding.rs` is exposed and compiled. Otherwise, it is not compiled and user can only use pure rust functions in core.rs.

**Comment by mejrs** [comment]
Yes, you can do that. You just need to make pyo3 an optional dependency and use a bunch of `cfg_attr`'s.

**Reply by NMZ0429** [reply]
Thank you for your answer. Could you elaborate it a bit more?
I actually tried to put `#[cfg(feature = "python")]` above `#[pyfunction]` and `#[pymodule]` then compile it with `maturin develop --features python` but it somehow raises segmentation fault at runtime in python.

Likely, my `Cargo.toml` is not correct. Could you please take a look at it?

```toml
[dependencies]
pyo3 = "0.19.0"
itertools = "0.10.1"
hashbrown = "0.14"
rand = "0.8.4"

[features]
python = [] 
```

My crate works after removing the feature flag and `#[cfg(feature = "python")]` .

**Reply by birkenfeld** [reply]
Can you reduce this to a minimal example and post it (all files including Carogo.toml)? It is hard to debug or reproduce without knowing how exactly you apply the feature.

**Reply by NMZ0429** [reply, marked as answer]
Thank you for your help. I eventually solved the problem by enabling `extension-module` feature of pyo3. So that `Cargo.toml` should look like below.

```toml
[dependencies]
pyo3 = { version = "0.19.0", optional = true, features = ["extension-module"] }

[features]
default = []
python = ["pyo3"]
```
