### DISCUSSION TITLE
Calling local python module from rust

### DISCUSSION THREAD

**Discussion by shot-codes** [PyO3/pyo3#3718] [Questions] [answered]
I'm attempting to call a function from a local python module in my rust code. (full code below). I've activated a virtual environment and installed the module with `pip install -e deconflict/`. My understanding from the pyO3 docs is that I should be able to use `PyModule::import` to import any modules available in my activated environment:
> [Pymodule::import](https://docs.rs/pyo3/0.20.1/pyo3/types/struct.PyModule.html#method.import) can be used to get handle to a Python module from Rust. You can use this to import and use any Python module available in your environment.

However, when I run my test Iget the error below. Note that I have verified the installation of my module by entering the python REPL and importing it there, with no issues. Any guidance would be much appreciated :)
```
---- tests::py_binding stdout ----
thread 'tests::py_binding' panicked at adder/src/lib.rs:32:25:
ModuleNotFoundError: No module named 'deconflict'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
.
├── adder/
│   └── src/
│       └── lib.rs
└── deconflict/
    ├── deconflict/
    │   ├── __init__.py
    │   └── add.py
    └── pyproject.toml
```
```rust
// adder/src/lib.rs

use ::pyo3::prelude::*;

pub fn add_numpy(a: i32, b: i32) -> PyResult<i32> {
    pyo3::prepare_freethreaded_python();
    Python::with_gil(|py| {
        let numpy_add = PyModule::import(py, "deconflict")?;
        let sum: i32 = numpy_add.getattr("add")?.call1((a, b))?.extract()?;
        Ok(sum)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn py_binding() {
        let res = add_numpy(40, 42);
        match res {
            Ok(val) => assert_eq!(val, 42),
            Err(err) => panic!("{}", err),
        }
    }
}
```
```python
# deconflict/deconflict/add.py

import numpy as np
from dataclasses import dataclass


@dataclass
class Response:
    label: str
    sum: int


def add(a: int, b: int) -> Response:
    array = np.array([a, b])
    return Response(label="hello world", sum=array.sum())
```
```python
# deconflict/deconflict/__init__.py

from .add import add
```
```toml
# pyproject.toml

[tool.poetry]
name = "deconflict"
version = "0.1.0"
description = "Deconfliction"
authors = ["shot-codes <some.email@gmail.com>"]
readme = "README.md"
packages = [{ include = "deconflict" }]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
