### DISCUSSION TITLE
What makes loading the NumPy array 5x slower than the Python list?

### DISCUSSION THREAD

**Discussion by christianrickert** [PyO3/pyo3#4732] [Questions] [answered]
I've run into an unexpected performance bottleneck with `pyo3` and `numpy`: In short, loading a large 2-dimensional `ndarray`into a Rust function takes about five times longer than a nested Python list.

```TOML
# Cargo.toml

[package]
name = "pyo3np"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyo3np"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"
```

```TOML
# pyproject.toml

[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "pyo3np"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
profile = "release"
features = ["pyo3/extension-module"]
```

```Rust
// lib.rs

use pyo3::prelude::*;

#[pyfunction]
fn return_vector(_input: Vec<Vec<f64>>) -> PyResult<()> {
    Ok(())
}

#[pymodule]
fn pyo3np(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(return_vector, m)?)?;
    Ok(())
}
```

```Python
# load_data.py

import pyo3np
import numpy as np
import time

# create random data
print("Creating data...", flush=True, end='')
np.random.seed(42)
input = np.random.rand(10, 1024 * 1024 * 100)#.tolist()
print("done.")

# load random data
print("Loading data...", flush=True, end='')
start = time.time()
pyo3np.return_vector(_input=input)
duration = time.time() - start
print(f"{duration}s.")
```

It takes about 25 seconds if I pass the `ndarray` to the `return_vector` Rust function:
```Terminal
Creating data...done.
Loading data...24.40405297279358s.
Creating data...done.
Loading data...25.127217292785645s.
Creating data...done.
Loading data...25.697571754455566s.
```
In contrast, it only takes about 6 seconds to load the same data as a Python list:
```Terminal
Creating data...done.
Loading data...5.6855690479278564s.
Creating data...done.
Loading data...5.770709037780762s.
Creating data...done.
Loading data...5.724390983581543s.
```

However, converting the `ndarray` to a Python list comes at the cost of (mostly) making a copy in memory, even without returning the processed data. - I did have a look at the [simple example](https://github.com/PyO3/rust-numpy/blob/main/examples/simple/src/lib.rs) for `rust-numpy`, but it adds a significant level of verbosity to the Rust code.

I'm glad that `pyo3` works out of the box with both `ndarray` and Python lists - even without any changes to the Rust code! But is there something I missed that could explain the difference in performance?
