### ISSUE TITLE
How to choose python3.5 or python2.7 with argument to execute script？

### ISSUE THREAD

**Issue by mokeyish** [PyO3/pyo3#104]
I have installed both python3.5 and python2.7.But the exmaple code choose python3.5 to execute.I cannot find the way to do use  python2.7 instead.

**Comment by fafhrd91** [comment]
you have to use "python2" feature:

```toml
[dependencies.pyo3]
version = "^0.2.3"
features = ["python2"]
```
