### ISSUE TITLE
Implementing #[pymethods] on a pyclass causes tests build to fail with linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by sbland** [PyO3/pyo3#1335]
using `#[pymethods]` with a simple pyclass is causing `cargo test` to fail with the below error:
`linking with `cc` failed: exit code: 1`

I followed the guide here for pyclass setup:
https://github.com/PyO3/pyo3/blob/master/guide/src/class.md#constructor

## cargo.toml
```toml
[package]
name = "hello"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3"
features = ["extension-module"]

[lib]
name = "hello"
crate-type = ["cdylib"]
```

## lib.rs
``` rust
extern crate pyo3;
use pyo3::prelude::*;

#[pyclass]
struct MyClass {
    num: i32,
}

/* Uncomment this block and it fails
#[pymethods]
impl MyClass {
    #[new]
    fn new(num: i32) -> Self {
        MyClass { num }
    }
}
*/

#[pymodule]
fn hello(py: Python, m: &PyModule) -> PyResult<()> {
    Ok(())
}

```

### 🌍 Environment

 - Your operating system and version: Ubuntu 20.04.1 LTS
 - Your python version: 3.8.6
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Python venv
 - Your Rust version (`rustc --version`): rustc 1.48.0 (7eac88abb 2020-11-16)
 - Your PyO3 version: "0.12.4"
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: Yes

**Comment by kngwyu** [comment]
Unfortunately, you need `--no-default-features`
https://pyo3.rs/v0.12.4/faq.html?highlight=test#i-cant-run-cargo-test-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror

**Comment by sbland** [comment]
Thanks for the solution. Unfortunately this does not seem to work if the library that uses`pyo3 is referenced from another rust library. I'm still learning rust so may have missed something but thought I'd mention it here.

**Comment by davidhewitt** [comment]
If you are able to modify the library using pyo3, you could add a feature to it which conditionally activates `pyo3/extension-module` - and then toggle that feature instead in the downstream library.

**Comment by sbland** [comment]
I resolved this by setting `default-features = false` in the config of the sub crate.
I.e.
Cargo.toml for parent crate:
``` toml
[dependencies]
sub_crate = { path = "../sub_crate", default-features = false }

```
