### ISSUE TITLE
Could not find Python on windows-latest

### ISSUE THREAD

**Issue by tushushu** [PyO3/pyo3#2778]
### Bug Description

When I tried to build my project in windows-latest by using Github action. It failed with the information as below:
```
Run maturin build --out dist -m ulist/Cargo.toml
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
💥 maturin failed
  Caused by: Finding python interpreters failed
  Caused by: Could not find any interpreters, are you sure you have python installed on your PATH?
Error: Process completed with exit code 1.
```
I never got this error before.

### Steps to Reproduce

Use the code block below to create a new Github action, replace the `anyproject` with yours and run it.
```
name: Unit Tests

on:
  pull_request:
  release:
    types: [published]

  workflow_dispatch:


jobs:
  pytest:
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Build
        run: |
          maturin build --out dist -m anyproject/Cargo.toml
```

My Github action `.yaml` file is here: https://github.com/Rust-Data-Science/ulist/blob/main/.github/workflows/main.yml
And my Github action error log is here: https://github.com/Rust-Data-Science/ulist/actions/runs/3533122507/jobs/5928343620

### Your operating system and version

Windows-latest

### Your Python version (`python --version`)

Python 3.9

### Your Rust version (`rustc --version`)

Github Rust toolchain

### Your PyO3 version

0.16.4

### How did you install python? Did you use a virtualenv?

Github action is using Pyenv I guess.
