### ISSUE TITLE
`2.5/3x` Performance regression with `PySequence as PyTryFrom` since `0.16`.

### ISSUE THREAD

**Issue by ritchie46** [PyO3/pyo3#2943]
This has been reported downstream in https://github.com/pola-rs/polars/issues/6791

It seems that dispatch to a very simple function has got a lot more expensive. Take this simple program:

```rust
use pyo3::prelude::*;
use pyo3::types::PySequence;

#[pyfunction]
fn get_len(obj: &PyAny) -> PyResult<usize> {
    let seq = <PySequence as PyTryFrom>::try_from(obj)?;
    seq.len()
}

#[pymodule]
fn pyo3_example(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(get_len, m)?)?;
    Ok(())
}
```

And running this snippet with a release build:

```
$ python -m timeit -n 1000000 -s "import pyo3_example as p; values = [1]" "p.get_len(values)"
```

This takes:

- 0.16: best of 5: 92.7 nsec per loop
- 0.17: best of 5: 255 nsec per loop
- 0.18; best of 5: 241 nsec per loop

## Cargo.toml

```toml
[package]
name = "pyo3-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyo3_example"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
```
