### ISSUE TITLE
datetime.date isinstance PyDateTime returns True?

### ISSUE THREAD

**Issue by MarcoGorelli** [PyO3/pyo3#3069]
### Bug Description

Given the example below, I would have expected
```Rust
my_date.is_instance_of::<PyDateTime>().unwrap()
```
to be `false`

### Steps to Reproduce

Here's my `main.rs` file:
```Rust
use pyo3::prelude::*;
use pyo3::types::{PyDateTime, PyDate};

fn main() -> () {
    Python::with_gil(|py| {
        let datetime = py.import("datetime").unwrap();
        let my_datetime = datetime.call_method1("datetime", (2022, 3, 28, 0, 0, 0, 0)).unwrap();
        println!("isinstance pydatetime: {:?}", my_datetime.is_instance_of::<PyDateTime>().unwrap());
        println!("isinstance pydate: {:?}", my_datetime.is_instance_of::<PyDate>().unwrap());

        let my_date = datetime.call_method1("date", (2022, 3, 28)).unwrap();
        println!("isinstance pydatetime: {:?}", my_date.is_instance_of::<PyDateTime>().unwrap());
        println!("isinstance pydate: {:?}", my_date.is_instance_of::<PyDate>().unwrap());
    })
}
```
Here's my `Cargo.toml` file:
```toml
[package]
name = "tmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.18.0", features = ["auto-initialize"] }
```

If I run the above, I get
```
isinstance pydatetime: true
isinstance pydate: true
isinstance pydatetime: true
isinstance pydate: true
```

I find this a bit odd, because running in Python directly, I get:
```python
In [27]: import datetime as dt

In [28]: isinstance(my_datetime, dt.datetime)
Out[28]: True

In [29]: isinstance(my_datetime, dt.date)
Out[29]: True

In [30]: isinstance(my_date, dt.datetime)
Out[30]: False

In [31]: isinstance(my_date, dt.date)
Out[31]: True
```

### Your operating system and version

Linux DESKTOP-U8OKFP3 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Your Python version (`python --version`)

Python 3.8.16

### Your Rust version (`rustc --version`)

rustc 1.68.1 (8460ca823 2023-03-20)

### Your PyO3 version

0.18.0

### How did you install python? Did you use a virtualenv?

virtualenv
