### ISSUE TITLE
to_pyarray method not found in nalgebra's Matrix

### ISSUE THREAD

**Issue by user529481** [PyO3/pyo3#4319]
I'm trying to return the output of some calculation from nalgebra, but I'm getting the following error:
```
[error[E0599]: no method named `to_pyarray` found for struct `nalgebra::Matrix` in the current scope
beta.to_pyarray_bound(py)
   |              ^^^^^^^^^^^^^^^^ method not found in `Matrix<f64, Dyn, Const<1>, VecStorage<f64, Dyn, Const<1>>>`

warning: unused import: `ToPyArray`
 --> src/lib.rs:2:26
  |
2 | use numpy::{IntoPyArray, ToPyArray, PyArrayDyn, PyReadonlyArrayDyn};
  | ](https://github.com/PyO3/pyo3/issues/4319#issue-2394157954)
```

This is the relevant portion of my code
```
...
let beta = if let Some(w) = criteria {
            ...
            xtwx.lu().solve(&xtwy).unwrap()
        } else {
            ...
            xtx.lu().solve(&xty).unwrap()
        };
beta.to_pyarray(py)
```
I've also tried `to_pyarray_bound`. From looking at the docs, there should be a method

> Integration with [nalgebra](https://docs.rs/nalgebra/0.32.5/x86_64-unknown-linux-gnu/nalgebra/index.html) is provided via an implementation of [ToPyArray](https://docs.rs/numpy/latest/numpy/convert/trait.ToPyArray.html) for [nalgebra::Matrix](https://docs.rs/nalgebra/0.32.5/x86_64-unknown-linux-gnu/nalgebra/base/matrix/struct.Matrix.html) to convert nalgebra matrices into NumPy arrays as well as the [PyReadonlyArray::try_as_matrix](https://docs.rs/numpy/latest/numpy/borrow/struct.PyReadonlyArray.html#method.try_as_matrix) and [PyReadwriteArray::try_as_matrix_mut](https://docs.rs/numpy/latest/numpy/borrow/struct.PyReadwriteArray.html#method.try_as_matrix_mut) methods to treat NumPy array as nalgebra matrix slices.

Source: 
https://docs.rs/numpy/latest/numpy/index.html

Here's my cargo.toml
```toml
[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustlib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.0"
nalgebra = "0.33.0"

[dependencies.numpy]
version = "0.21"
features = ["nalgebra"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
bindings = "cffi"
compatibility = "linux"
```
