### ISSUE TITLE
Add supported CPython/PyPy versions to cargo package metadata

### ISSUE THREAD

**Issue by messense** [PyO3/pyo3#4751]
https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table

Currently `maturin` hardcodes minimal supported interpreter versions based on pyo3 versions, it'd be nice if this information is encoded in cargo package metadata of `pyo3` and `pyo3-ffi` so we can make it future-proof in `maturin`.

For example:

```toml
[package.metadata.cpython]
version = ">=3.7,<3.14"

[package.metadata.pypy]
version = ">=3.9,<3.11"
```
