### ISSUE TITLE
bump minimum hash brown version to 0.15

### ISSUE THREAD

**Issue by joseluis** [PyO3/pyo3#4877]
### Bug Description

There's a combination of dependencies and features that fails to compile, due to the minimum version for the `hashbrown` crate.

The easiest solution is to bump `hashbrown` versioning from `">= 0.14.5, < 0.16"`. to `">= 0.15.0, < 0.16"` (fortunately 0.15.0 has the same MSRV of 1.63.0 as `pyo3` does).

### Steps to Reproduce

1. create a new cargo project with this manifest:

`Cargo.toml`
```toml
[package]
name = "pyo3-hashbrown-nightly"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = {version = "0.15", features = ["nightly"] }
pyo3 = { version = "0.23.4", features = ["hashbrown"] }
```

2. run:
```
cargo +nightly update -Z minimal-versions
cargo +nightly build
```

### Backtrace

```shell

```

### Your operating system and version

linux 5.15

### Your Python version (`python --version`)

Python 3.10.12

### Your Rust version (`rustc --version`)

rustc 1.86.0-nightly (2f348cb7c 2025-01-27) 

### Your PyO3 version

0.23.4

### How did you install python? Did you use a virtualenv?

n/a
