### ISSUE TITLE
`multiple-pymethods` results in macro panics on certain `inventory` versions

### ISSUE THREAD

**Issue by ADSteele916** [PyO3/pyo3#4950]
### Bug Description

On Rust 1.79 and later, versions of the `inventory` crate before `0.3.5` (`pyo3` currently requires `^0.3.0`) cause any `pymethods` attribute macros to panic during evaluation.

### Steps to Reproduce

1. Create a Rust crate with the following `Cargo.toml`:
```toml
[package]
name = "pymethods"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.5", features = ["multiple-pymethods"] }
inventory = "=0.3.4"
```
and `lib.rs`:
```rust
use pyo3::prelude::*;

#[pyclass]
pub struct MyStruct {}

#[pymethods]
impl MyStruct {
    pub fn foo(&self) {}
}
```
2. Run `rustup toolchain add 1.79.0-x86_64-unknown-linux-gnu`.
3. Execute `cargo +1.79.0-x86_64-unknown-linux-gnu check`.

### Backtrace

```shell
error: custom attribute panicked
 --> src/lib.rs:6:1
  |
6 | #[pymethods]
  | ^^^^^^^^^^^^
  |
  = help: message: Unrecognized literal: `c"foo"`
  = note: this error originates in the macro `::pyo3::inventory::submit` which comes from the expansion of the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Your operating system and version

Ubuntu 22.04

### Your Python version (`python --version`)

N/A

### Your Rust version (`rustc --version`)

1.79+

### Your PyO3 version

0.23.5

### How did you install python? Did you use a virtualenv?

N/A

### Additional Info

I can make a PR bumping the version of `inventory` to `0.3.5`, but I wanted to check if there's a way the maintainers would rather handle the issue, since it doesn't affect older Rust versions.
